### ISSUE TITLE
Use Vega-Lite layering to support tooltip on line charts and area charts

### ISSUE THREAD

**Issue by ZeningQu** [vega/vega-tooltip#1]
Currently tooltip for line chart does not report correct data because data is bound to path, not to points. In the screenshot below, price should be a number around 200 and date should be in human-readable format (that's another issue).
![screen shot 2016-02-28 at 1 17 04 pm](https://cloud.githubusercontent.com/assets/822034/13382124/83c01ede-de21-11e5-8a22-7ba1b53242ad.png)

**Comment by kanitw** [comment]
This will be partially addressed by https://github.com/vega/vega-lite/issues/508

**Comment by kanitw** [comment]
This will be partially addressed by fixing https://github.com/vega/vega-lite/issues/508, but we should wait until we have layering support first.

**Comment by kanitw** [comment]
One thing that we can do now is

- [ ] from the `item` parameter we get.  Is there a way to know that the mark is a line, then we can drop quantitative values?

**Comment by ZeningQu** [comment]
Partially fixed in PR #16, which only displays qualitative fields for line charts and area charts, and gives warnings in the console.

**Comment by kanitw** [comment]
Hmm.  If it is *partially* fixed and should be further fixed, I don't think we should close it.

**Comment by ZeningQu** [comment]
Dropping quantitative fields does seem to solve the problem for the `line_color` example we have above, but if the `stocks.csv` data set contains some additional qualitative fields, shouldn't those fields be dropped too? An additional field's value will vary for a line/area mark, but before we add layering support, tooltip will only pick up one datum for a line/area mark, which may be inaccurate. 

As a better partial fix, we may drop fields in the x and y channels and only show fields in the other encoding channels (typically color). In this way, if a qualitative field is not used for encoding, it will not show up in the tooltip.

I am writing down this thought for logging purpose. I know we will have layering really soon, so we may not even need to implement this "better partial fix" -- we may go straight into "using layering to properly show all fields" for line charts and area charts.

I wrote down these thoughts as comments in PR #16.

**Comment by ZeningQu** [comment]
Close via #50
