### ISSUE TITLE
Creating vega-tooltip on Vega 2.X

### ISSUE THREAD

**Issue by lemoncyb** [vega/vega-tooltip#103]
I noticed that vega-tooltip can be created with Vega 3.0 view API like this:
```
var runtime = vega.parse(vgSpec);
var view = new vega.View(runtime)
  .initialize(document.querySelector(id))
  .hover()
  .run();
vegaTooltip.vega(view, options); // pass in options
```

I'm wondering is it possible to create vega-tooltip on Vega 2.X runtime API. I tried this but it didn't work.
```
function parse(spec) {
  vg.parse.spec(spec, function(error, chart) { 
    var view = chart({el:"#vis"})
      .initialize(document.querySelector("#vis"))
      .update(); 

    vegaTooltip.vega(view);
  });
}
parse("uri/to/your/vega/spec.json");
```

**Comment by domoritz** [comment]
I just added a note to the docs. Please use the [previous version of Vega-Tooltip](https://github.com/vega/vega-tooltip/releases/tag/v0.1.3) or upgrade to Vega 3 and Vega-Lite 2.
