### ISSUE TITLE
add a minified version of css

### ISSUE THREAD

**Issue by sorenmacbeth** [vega/vega-tooltip#104]
I know it's a small file, but it would be good to have a minified css along with minified js for production purposes.

**Comment by domoritz** [comment]
We are working on reducing the size of the library. This is definitely one important step. Do you want to submit a pr?

**Comment by sorenmacbeth** [comment]
I can try, but my javascript tool chain experience is extremely limited. I'll report back here if I get stuck.

**Comment by sorenmacbeth** [comment]
submitted PR #105
