### ISSUE TITLE
provide a vegaTooltip() wrapper function which takes `$schema` into account

### ISSUE THREAD

**Issue by g3o2** [vega/vega-tooltip#113]
It would be convenient if there existed a wrapper function, which based on the `$schema` property, would choose the applicable flavour itself. Instead of having to call `vegaTooltip.vega()` or `vegaTooltip.vegaLite()`, one would simply be able to call `vegaTooltip()`. If the `$schema` property is absent, an error should be thrown by the wrapper function.

Right now, depending on the flavour used, i.e. vega or vega-lite, one has to specify the function explicitly, which is nice for programmers but more burdensome for non-programmers.

**Comment by domoritz** [comment]
I think we're going to add tooltips to vega-embed instead that already knows whether the spec is Vega or Vega-Lite. What do you think?

**Comment by g3o2** [comment]
Good idea. In vega-embed, there is already a corresponding [issue](https://github.com/vega/vega-embed/issues/14) ;)

Maybe most non-programmers don't even know how to use stand-alone vega-tooltip anyway. In that case I'm not sure whether a wrapper would  matter to anyone else.

**Comment by domoritz** [comment]
Let me close this issue then.
