### ISSUE TITLE
vega 2 compatible vega-tooltip version 0.1.3 not available on cdnjs

### ISSUE THREAD

**Issue by g3o2** [vega/vega-tooltip#119]
The vega-tooltip version 0.1.3, which is compatible with the stable versions of vega 2 and vega-lite 1, is not available on [cdnjs](https://cdnjs.com/libraries/vega-tooltip). Would it be possible to upload the said version with its corresponding files (css, etc.) ? Or have I missed how to make the undocumented version 0.2.0 work with the said vega version ?

**Comment by g3o2** [comment]
@sirahd for documentation purposes, I add here that the issue has been fixed on the jsdelivr platform Thank you!

**Comment by domoritz** [comment]
https://github.com/vega/vega-tooltip/commit/eaae4069047583d367e2cab5f9daa4c67842aa0a was the commit for the rewrite so the version before then should be the last that works with Vega 2.
