### ISSUE TITLE
In vega-lite, in when using line chart, tooltip shows same value at any point

### ISSUE THREAD

**Issue by taleodor** [vega/vega-tooltip#120]
This may be observed in the vega-tooltip project demo page, looking at the line chart demonstration with stocks. 
Steps to reproduce:
1. Move cursor along any stock line. 
2. Notice that the tooltip value is not changing in any point of the line.

**Comment by domoritz** [comment]
Explanation and fix in https://github.com/vega/vega-tooltip/issues/68. Hopefully, there will be a cleaner and easier solution in the future.

**Comment by taleodor** [comment]
Hi Dominik,

Thanks a lot for the quick response, but I believe this issue is a little different (although core reason may be the same, not sure about it). Basically, this one is not about difficulties in getting tooltip to show up but the fact that the tooltip has exactly same value at any point of a single line. I'm attaching screenshots from your demo page to make it more visible -> notice that the tooltip shows exactly same value in the leftmost and rightmost points of the GOOG line.

![image](https://user-images.githubusercontent.com/3857268/28519416-73bf6570-7039-11e7-81cb-c6dd424a967a.png)

![image](https://user-images.githubusercontent.com/3857268/28519421-7b63ca96-7039-11e7-8957-fba78fadf49c.png)

**Comment by kanitw** [comment]
This is currently a limitation in the underlying Vega where lines are output as a single mark instance.
The solution is to add a layer of points so that you can overlay.   

@sirahd  -- we should better document and add warning about this.

**Comment by kenklin** [comment]
@kanitw "The solution is to add a layer of points so that you can overlay." I am using Vega 3 an experience this same problem with toolTip.
- Would I use Vega's [group](https://vega.github.io/vega/docs/marks/group/) instead of layer?
- Is there a Vega 3 example of toolTip with line marks?

**Comment by domoritz** [comment]
You can use Vega-Lite to compile a Vega spec and see for yourself what code
we generate.

For this specific example, you don't even need a new group. Just add a
point Mark in addition to your path.

**Comment by domoritz** [comment]
We are working on solutions for this in Vega and Vega-Lite.

**Comment by onehost1** [comment]
@domoritz has the new update for Vega and Vega tooltip fixed this issue as well? My implementation of latest update doesn't seem to notice any difference on this side.

All in all, new tooltip looks great!

**Comment by domoritz** [comment]
@onehost1 Thank you. The next Version of Vega will come with a solution to this. With the new tooltips, it now makes sense to resolve this issue in Vega.

**Comment by xinxingliu90** [comment]
@domoritz I used vega-embed(latest version 3.15.0) to render the line charts, and has the same issue that tooltip shows the same value at every point. But when I click "open vega editor", the tooltip changes with different point mouse-over.

Does vega-embed also includes the fix for this tooltip issue?

**Comment by domoritz** [comment]
You need to use Vega 4.

**Comment by xinxingliu90** [comment]
@domoritz Thanks for quick reply! Just make sure, are you saying I need use vega api to render the chart, instead of vega-embed?

**Comment by domoritz** [comment]
Vega embed uses Vega but it works with Vega 3 and Vega 4 and so I'm asking about the Vega version.

**Comment by xinxingliu90** [comment]
Problem solved, thank you @domoritz !
