### ISSUE TITLE
disable tooltip based on mark property (e.g. opacity)

### ISSUE THREAD

**Issue by lukasheinrich** [vega/vega-tooltip#121]
For interactive/busy visualizations, it's useful to be able to toggle the visibility of marks. It would be nice if one could control whether the tool-tip appears or not based on mark properties such as the opacity.

The interactive cars scatter plot is a good example where this would be useful.

**Comment by kanitw** [comment]
> For interactive/busy visualizations, it's useful to be able to toggle the visibility of marks.

You can use filter transform in Vega-Lite to filter things for being displayed. 

> It would be nice if one could control whether the tool-tip appears or not based on mark properties such as the opacity.

This more general support for showing tooltip based on mark property can be problematic when you create a visualization for public audience.  They might get confused why certain marks have tooltips and some do not.  Thus, I think using filter is a better way.
