### ISSUE TITLE
How to specify signal for options.fields field value?

### ISSUE THREAD

**Issue by kenklin** [vega/vega-tooltip#127]
In my tooltip's [`options.fields`](https://github.com/vega/vega-tooltip/blob/master/docs/customizing_your_tooltip.md) array I would like to use a Vega 3 [signal](https://github.com/vega/vega-tooltip/blob/master/docs/customizing_your_tooltip.md).  In theory, something like this ...

    var tooltipOption = {
        showAllFields: false,
        fields: [
            {field: "c", title: "Car"},
            {field: {signal: "MySignal"}}
       ]
    };

Is there a way I can do something like this?

**Comment by kanitw** [comment]
I'm not sure if this is a generally useful feature to add (and it will be quite complicated to add).  I will have to see example use case to determine if it is.  

In any case, for now, maybe you can add a `formula` transform to your Vega spec to add a new field that has value based on the signal `MySignal`.  

```
{"type": "formula", "as": "MySignalField", "expr": "MySignal"}
```

This way your data will have the field `MySignalField` that you can access via vega-tooltip.

**Comment by ericsoco** [comment]
@kenklin would [title/value accessors](https://github.com/vega/vega-tooltip/pull/155/) be useful for your use case?
