### ISSUE TITLE
Integrate Vega Tooltip with other systems

### ISSUE THREAD

**Issue by kanitw** [vega/vega-tooltip#13]
Once we're done with everything else in [1.0 milestone](https://github.com/vega/vega-lite-tooltip/milestones/1.0).  

We should integrate this with
- [x] VLUI (hence Voyager and Polestar)

and maybe:
- [x] Vega-Lite docs
- [x] Vega-Editor

**Comment by Georgeouz** [comment]
and maybe vega-embed ? ;-)
