### ISSUE TITLE
Specifying `options` without `fields` throws JS error

### ISSUE THREAD

**Issue by ericsoco** [vega/vega-tooltip#133]
There's no guard in [parseOption::prepareCustomFieldsData()](https://github.com/vega/vega-tooltip/blob/master/src/parseOption.ts#L58) against a missing `fields` field in passed `options`, though all of the fields of `options` are considered optional according to the docs.

Simple workaround is to add an empty array, but this shouldn't be required.

**Comment by domoritz** [comment]
Yeah, we should use default arguments.
