### ISSUE TITLE
Can't follow usage examples and tooltips not working on latest

### ISSUE THREAD

**Issue by hipitihop** [vega/vega-tooltip#140]
Is anyone using Vega | Vegalite with vega-tooltip plugin in ClojureScript ? or is otherwise using the plugin with success and willing to share a code snippet ?

I have had success using both Vega & VegaLite including the vega-embed plugin from ClojureScript via the CLJSJS Packages project https://github.com/cljsjs/packages but I can't get the vega-tooltip plugin to work. Extract of ClojureScript code using a Reagent/React component:

```clj
(reagent/create-class
  {:reagent-render      (fn [] [:div#vpart1])
   :component-did-mount (fn [comp]
                           (let [spec (clj->js v-data)]
                            (.then
                              (js/vegaEmbed "#vpart1" spec #js{"mode" "vega-lite" "actions" false})
                              (fn [result]
                                (let [view     (gobj/get result "view")
                                      vegaLite (.-vegaLite js/vegaTooltip)]
                                  (vegaLite view spec #js{"showAllFields" true}))))))}))
```
 
While my vega-lite chart displays as as expected, there is no hover going on. The vega-tooltip examples like this one https://github.com/vega/vega-tooltip/blob/master/docs/creating_your_tooltip.md#step-3-create-a-tooltip seem a bit confusing since they use `vega.embed` which does not exist So I'm wondering are the main Vega libraries ahead of these examples or am I missing another incantation.

The vega examples and vega-editor also don't make it obvious as to how they engage the tooltip plugin.

I'm using:
vega 3.0.7
vega-lite 2.0.0
vega-embed 3.0.0
vega-tooltip 0.4.4

Any pointers appreciated.

**Comment by kanitw** [comment]
@hipitihop -- thanks for reporting.  Btw, to help us help you,  it might be good if you can provide a snippet in Javascript that we can use to re-produce the problem as our team are not familiar with ClojureScript.  Thanks!


@sirahd  -- can you take a look into this once @hipitihop replies?

**Comment by domoritz** [comment]
I updated the versions in c616fb0b631268d5fda83be5035441a2fd64fc5f. Let me know if it works now.

**Comment by bpiel** [comment]
@hipitihop did you ever get this working?

**Comment by hipitihop** [comment]
@bpiel Apologies for the lack of responses. I have not had time to get back to investigating this issue due to other commitments. It will probably be another 6 weeks or so before I do. We have updated our project to use `vega "3.3.1"` `vega-embed "3.16.1"` and `vega-tooltip "0.12.0"` but no time yet to look at activating custom tips. I'll report here when I cycle back.
