### ISSUE TITLE
Dates are not formatted

### ISSUE THREAD

**Issue by domoritz** [vega/vega-tooltip#146]
https://vega.github.io/editor/#/examples/vega-lite/line_step

<img width="417" alt="screen shot 2018-01-25 at 15 20 41" src="https://user-images.githubusercontent.com/589034/35417682-5c42b294-01e3-11e8-9bde-d061656c3ff5.png">

**Comment by jheer** [comment]
Ah `1.2674304e+12`... it was the best of times, it was the worst of times.

**Comment by domoritz** [comment]
Next IDL group meeting at 1.516924e+12.

**Comment by domoritz** [comment]
Ahh, problem is that the Vega editor assumes that the spec is Vega and doesn't pass the Vega-Lite spec into it.
