### ISSUE TITLE
Disable tooltip by layer

### ISSUE THREAD

**Issue by eibanez** [vega/vega-tooltip#148]
It would be nice to disable the tooltip for certain marks. For instance the following geo example has a tooltip for states, but those don't add any information.
https://vega.github.io/editor/#/examples/vega-lite/geo_rule

![image](https://user-images.githubusercontent.com/438494/35582505-a6703b28-05b4-11e8-9c70-2aa60225e621.png)

Perhaps something like setting the "tooltip" channel to "false" or "null" could disable it?

**Comment by ericsoco** [comment]
Another example use case: I just added legend filtering (similar to [this Vega example](https://vega.github.io/vega/examples/interactive-legend/)) and am getting warnings `Cannot find field foo in data.` Perhaps a tooltip config to gate tooltip mouseover/out handling on an [event stream selector](https://vega.github.io/vega/docs/event-streams/#event-stream-selectors) would help?

https://github.com/vega/vega-tooltip/issues/39

**Comment by sirahd** [comment]
@eibanez If you look at the documentation (https://github.com/vega/vega-tooltip/blob/master/docs/APIs.md#vgtooltip), there is `showAllFields` flag in option you can set to show only certain field in the tooltip

**Comment by ericsoco** [comment]
@sirahd you're right that `showAllFields` + `fields` should handle @eibanez' use case. Should I create a separate ticket for mine?

Also, I did a quick skim to see how event stream selectors might be implemented for vega-tooltip, and I see you're using Vega View's `addEventListener` directly, so I wasn't sure where selectors would plug in. If you agree this is a good direction and have some pointers I might be able to look into it.

That said, maybe it's better to pair this with #151?

**Comment by sirahd** [comment]
It seems like Vega-scenegraph only supports standard DOM event types (`mouseover`, `click`, etc.), which is different from [Event Stream Selector](https://vega.github.io/vega/docs/event-streams/#event-stream-selectors), which is used internally by Vega for signal. I'm not quite certain if what you said is possible since it seems like Vega-view doesn't currently have support for custom event selector (https://vega.github.io/vega/docs/api/view/#view_events)

**Comment by eibanez** [comment]
I have another case that cannot be solved by the suggestions above: in the following plot I want the tooltip for the circle mark but not for the line mark.

```
{
  "$schema": "https://vega.github.io/schema/vega-lite/v2.json",
  "description": "Google's stock price over time.",
  "data": {"url": "data/stocks.csv"},
  "transform": [{"filter": "datum.symbol==='GOOG'"}],
  "layer": [{
    "mark": "line",
    "encoding": {
      "x": {"field": "date", "type": "temporal", "axis": {"format": "%Y"}},
      "y": {"field": "price", "type": "quantitative"}
    }
  },
  {
    "mark": "circle",
    "encoding": {
      "x": {"field": "date", "type": "temporal", "axis": {"format": "%Y"}},
      "y": {"field": "price", "type": "quantitative"}
    }
  }]
}
```

**Comment by domoritz** [comment]
I think we should investigate the use of the tooltip channel for this kind of stuff. This way you can exactly specify where you want tooltips and where not.

**Comment by domoritz** [comment]
See related issue: https://github.com/vega/vega-tooltip/issues/151

**Comment by kanitw** [comment]
or the `metadata` / `userdata` field that we discussed somewhere (couldn't find the issue).   

(This way, vega tooltip can expect to have some extra properties that are not really property of normal VL/VG specs.)

**Comment by alexchantastic** [comment]
Would this allow disabling tooltips for legends?

**Comment by alexchantastic** [comment]
Hm... I'm not sure if I'm initializing them in a weird way, but here's an Observable notebook I've been building to get more familiar with Vega: https://beta.observablehq.com/@alexchantastic/vega-charts

In all of the charts that have legends, tooltips appear when the legend encoding has `interactive: true`.

**Comment by domoritz** [comment]
Hmm, that could be because you made the legends interactive. Can you file this as a separate issue? 

Btw, these charts look amazing and I love the legend interactions. If you want, you could implement this feature in Vega-Lite: https://github.com/vega/vega-lite/issues/1657.

**Comment by alexchantastic** [comment]
@domoritz thanks for the quick replies. I've created #170 to track the legend issue separately.

I'll see if I can find some time to implement the legend interactions in Vega-Lite 👍.

**Comment by kanitw** [comment]
If tooltip channel is `null` as discussed in https://github.com/vega/vega-lite/issues/3560, then the Vega-Tooltip should know to hide the tooltip for that single view plot.
