### ISSUE TITLE
Evaluate tooltipHandler

### ISSUE THREAD

**Issue by domoritz** [vega/vega-tooltip#151]
Evaluate whether it makes sense to use https://vega.github.io/vega/docs/api/view/#view_tooltipHandler.

**Comment by sirahd** [comment]
This seems like a good idea. Right now what we do is just setting the event listener directly on Vega View on mouseover, mousemove and mouseout. Using this internal event handler would be more conventional way to do it.

**Comment by domoritz** [comment]
Awesome. Thanks for looking into it!
