### ISSUE TITLE
/build is committed only on tag commits

### ISSUE THREAD

**Issue by ericsoco** [vega/vega-tooltip#160]
This is probably by design, but it's not possible to `npm`/`yarn` install a specific non-tagged commit because the `/build` folder is only committed via the `deploy` script (which `npm publish`es with a new tag).

I'm trying to pull my recent contributions into my application, but since untagged commits have no `/build` folder, I can't do so.

(Also file under...when do you plan to cut a new version? 😉)

**Comment by domoritz** [comment]
Yeah, this is by design. I defer the other question to @sirahd

**Comment by ericsoco** [comment]
I pushed `build` to a branch on my fork and that works for me for now, so there's no rush.

**Comment by domoritz** [comment]
We just made a release.
