### ISSUE TITLE
vega-tooltip isn't working in my React application

### ISSUE THREAD

**Issue by EpsApps** [vega/vega-tooltip#162]
Hi, I'm having issues making vega-tooltip work in my React application. Vega itself works well. I've followed the documentation in implementing it. These are my dependency versions:

react: 16.2.0
vega: 3.1.0
vega-tooltip: 0.5.1

This code fires in componentDidUpdate after the vega view's container is rendered:
``` javascript 
let vegaView = new vega.View(vega.parse(this.vegaSpec()))
   .initialize(this.refs[this.state.ref])
   .hover()
   .run();
this.setState({ initializedVega: true });
this.vegaView = vegaView;
vegaTooltip.vega(this.vegaView);
```

I've tested this with a spec provided here: https://vega.github.io/editor/#/examples/vega/line-chart.

Thank you!

**Comment by domoritz** [comment]
Are you importing the css as well?

**Comment by EpsApps** [comment]
@domoritz thank's for pointing this out... I never imported the css. Your help is much appreciated.
