### ISSUE TITLE
remove explicit dependency on `vega` (to support drop-in `vega-lib`)

### ISSUE THREAD

**Issue by tvald** [vega/vega-tooltip#165]
After looking through the source, I believe the listed production dependency on `vega` may be unnecessary. The explicit dependency is also undesirable because it negates the benefit of using the lightweight `vega-lib` in place of the full `vega`.

**Comment by domoritz** [comment]
Thank you for the issue. Do you suggest that we switch to vega-lib? We can definitely do that.

**Comment by tvald** [comment]
I don't think you need to explicitly depend on either, which would allow projects to choose the variant they want to use.

**Comment by pelotom** [comment]
It seems like both `vega-tooltip` and `vega` should depend on `vega-lib`, or am I wrong?

**Comment by tvald** [comment]
`vega` does not depend on `vega-lib`:

[vega/vega#1073](https://github.com/vega/vega/issues/1073#issuecomment-366813633)
> nyurik:
> Should vega depend on vega-lib to minimize potential build / code synchronization issues?

[vega/vega#1073](https://github.com/vega/vega/issues/1073#issuecomment-366814936)
> jheer:
> My original thinking was "yes", but then I changed my mind when I went to implement this. For the time being I found it more convenient to manage all the example specs (including those in both tests and documentation) from a single repo (Vega), test them all together prior to release, then release vega-lib in parallel. I'm open to revisiting this later on, though.

**Comment by domoritz** [comment]
We can change Vega-Tooltip to depend on Vega-Lib. We do need some functionality of Vega but we don't actually compile Vega into the package (like Vega-Embed). I noticed an issue with typings when supporting both Vega and Vega-Lib (https://github.com/vega/vega-typings/issues/13), though.
