### ISSUE TITLE
valueAccessor of field options is never called

### ISSUE THREAD

**Issue by nextminds** [vega/vega-tooltip#166]
It looks like the `valueAccessor` function on field options is never called.

I think the `valueAccessor` gets lost from the  `fieldOption` when it goes through `supplementFieldOption`. Later in during parseOption, when the `valueAccessor` is used, it's never there.

jsfiddle to demonstrate: https://jsfiddle.net/3jgeyze6/13/

Or am I misunderstanding how `valueAccessor` should work?

**Comment by ericsoco** [comment]
No, I think you're right -- when I issued this PR I was only looking at the Vega codepath and missed this Vega-Lite codepath. It does look like `supplementFieldOption` ignores `valueAccessor` and then `supplementOptions` returns `options.fields` without it.

I'm planning to spend time next week on adding examples for `valueAccessor` and things from my other related PRs, will try to address this as well.
