### ISSUE TITLE
Tooltip Title

### ISSUE THREAD

**Issue by Casyfill** [vega/vega-tooltip#171]
it would be great to be able to render a "title" of the element, e.g. 
if I have a map of neighborhoods, It would be great to have a proper title as part of the tooltip (as an opposite to one-of value in a table, by adding a corresponding flag/property to the specs. 

I can "render"  title for given field using `render` property, but 1) it will still be part of the table, if I understand correctly, and 2) I can imagine this option bein fairly typical, anyway

**Comment by domoritz** [comment]
This is a fantastic idea. How do you propose to change the API?

**Comment by Casyfill** [comment]
probably we can just add `title:true` flag (and perhaps `subtitle:true`) to the field object, but I understand this might be a slippery slope; I wonder if there are javascript templating solutions (so that we can feed template to the tooltip, instead), similar to Jinja, available....

**Comment by Casyfill** [comment]
As for now I kinda achieved this goal via render (thanks to `colspan=2`)!:

```
{
                "field": "Neighborhood",
                "title": "Name",
                "formatType":"str",
                "render": {"arguments":"title, value",
                           "body":"return document.createElement('h5').appendChild(document.createTextNode(value))"}
              },
```

and then had to process all render objects into functions

**Comment by nyurik** [comment]
Data should be specified by Vega spec, not by external options. We could introduce "magical parameter":
```js
tooltip: {
  signal: "  { '%%title': 'my title',  'field1': datum.field1 } "
}
```

**Comment by domoritz** [comment]
Yes, @kanitw and I discussed exactly this just a few minutes ago. Magic names seem like the best option for this.
