### ISSUE TITLE
tooltip options as part of the vega/vega-lite specs

### ISSUE THREAD

**Issue by Casyfill** [vega/vega-tooltip#172]
it would be nice for vega/vl specs to officially support tooltip options - so far I keep them within `usermeta` section of the specs, get them within my javascript and feed them to the tooltip plugin,
but I don't see any reason why plugin can't check for those options automatically

**Comment by domoritz** [comment]
Thanks for the issue. See discussion in https://github.com/vega/vega-lite/issues/3560. I'm going to close this to keep it in one place.
