### ISSUE TITLE
Cannot copy from tooltip

### ISSUE THREAD

**Issue by domoritz** [vega/vega-tooltip#186]
The tooltip disappears when you hover over the tooltip itself.

**Comment by nyurik** [comment]
I have spoken with my colleagues about this. They actually think this will be counterintuitive. They proposed a different workflow: require user to click something for a different type of tooltip to show up - a "modal" one -- it doesn't close on mouseout, maybe has a close button, possibly closes on click outside.

@jheer can you think of a good way for tooltip to implement this behavior?   Of course I could implement it via custom expressions, but it seems this could benefit others too.

**Comment by domoritz** [comment]
Wouldn't click interfere with other custom behavior? I'd rather not let people copy from tooltips.

**Comment by nyurik** [comment]
@domoritz of course - I think it should be in the hands of the graph designer to decide - to allow modal tooltips or not handle click in some other way.   Thing is, with custom tooltip handler (not vega-tooltip), this becomes a good mechanism for complex custom popups with rich HTML.  At this point, there is no such functionality in Vega.

**Comment by domoritz** [comment]
You could attach a click handler to the view, I guess.

**Comment by nyurik** [comment]
@domoritz sure, but the whole idea here is that handler shouldn't have any "business" logic - Vega spec should decide when it should get called.   I outlined it in the above issue on vega repo

**Comment by domoritz** [comment]
I really don't think this is a common use case and would rather keep Vega and Vega-Tooltip clean. You can build it with the existing handlers if you really need to.

**Comment by jdb** [comment]
@domoritz can you elaborate on what the use case for tooltip is for you and provide a pointer on the existing handlers that can be used to provide the feature. 

In many viz, I show a time series of the count of events. The tooltip shows the list of events id when hovering on a date, so we can further investigate each event. The ids can not be memorized easily, hence the need to copy paste. I think ideally, this viz would have 2 frames, with the timeseries on the left, and on the right, I could read and copy/paste the list of ids corresponding to the ponit that the user has clicked on, in the right frame. 

TIA
