### ISSUE TITLE
Tooltip does not hide if View is destroyed

### ISSUE THREAD

**Issue by nyurik** [vega/vega-tooltip#190]
If page re-generates Vega graph, it is expected for the tooltip to hide, even if the mouse is underneath.

Repo:   use graph from #189 -- move the mouse over the graph, but keep the focus in the editor. Observe tooltip value.  Now, without moving the mouse, change vega spec's tooltip signal to return `null` - now the graph has been regenerated, and does not try to show the new tooltip even as the user moves the mouse. But that keeps the old tooltip visible.

Should we bring back `dispose` ?

**Comment by nyurik** [comment]
Cc @jheer - we may need onDestroy from Vega?

**Comment by jheer** [comment]
I can update vega-view to invoke the tooltip handler with value `null` upon finalization... shouldn’t require changes anywhere else.
