### ISSUE TITLE
Vega lite tooltip no longer working?

### ISSUE THREAD

**Issue by kmcmorrow1** [vega/vega-tooltip#196]
Was there an update today? Seems that the Vega Lite tooltip is no longer working. I am receiving the error: "TypeError: vegaTooltip.vegaLite is not a function", when the same code worked two days ago.

**Comment by kanitw** [comment]
@domoritz rewrote a better version of tooltip, with new APIs, but this include breaking changes. 

@domoritz -- could you please add a note to the release page about the new API?

**Comment by kanitw** [comment]
For now, you can look at README to see how to use the API.

**Comment by domoritz** [comment]
Thanks for reporting the issue @kmcmorrow1! I fixed the example page and removed examples that don't yet have tooltips.

**Comment by kmcmorrow1** [comment]
@domoritz I'm very new to working with Vega Lite--and I can't seem to figure out the new tooltip call. Is there any chance you can help me figure out how to incorporate the new version of the tooltip into my current plot? It is a choropleth map, and the original call (which was working before) looked like this:

vegaEmbed("#vis", vlSpec, opt).then(function (result) {
      var tooltipOption = {
    	showAllFields: false,
    		fields: [
      		{field: "state", title: "State"},
          {field: "market", title: "Market"}
    		]
  		};
      vegaTooltip.vegaLite(result.view, vlSpec, tooltipOption);
    }).catch(console.error);


Thank you so much.

**Comment by domoritz** [comment]
@kmcmorrow1 Welcome to Vega-Lite! If you use the latest version of Vega-Embed, you don't need to install anything -- you already have vega tooltip. Check out https://vega.github.io/vega-lite/docs/tooltip.html for details about how to add tooltips to Vega-Lite charts. 

You can read more about the changes at https://github.com/vega/vega-tooltip/wiki/Changes-in-Vega-Tooltip-0.9.

**Comment by kmcmorrow1** [comment]
@domoritz Amazing! That worked perfectly. Thank you so much.
