### ISSUE TITLE
vega-embed action buttons disappear when switching between vega-tooltip versions 0.8 and 0.9

### ISSUE THREAD

**Issue by g3o2** [vega/vega-tooltip#199]
chosen method of including vega-tooltip:

```javascript
vegaEmbed(...)
.then(function(result) {
  vegaTooltip.default(result.view, tooltip_options)
}
```

The plot is rendered but the action buttons are simply not when using version 0.9 of vega-tooltip, while with vega-tooltip 0.8 or earlier everything renders as expected.

Maybe I have missed taking into account another API change between 0.8 and 0.9 ?

FYI, I am using vega@3.3, vega-lite@2.4 and vega-embed@3.7.

**Comment by domoritz** [comment]
I'll look into this. As a side note, Vega embed now comes with Vega tooltip by default so you don't even have to install it.

**Comment by g3o2** [comment]
Thank you, @domoritz! I have removed the reference to the vega-tooltip script and now it works indeed as expected. Maybe vega-embed uses an older version of vega-tooltip ? If it does not, then I guess the issue is solved.

**Comment by domoritz** [comment]
Great! I just pushed a new version with the latest tooltip library.
