### ISSUE TITLE
Move tooltips as the cursor moves

### ISSUE THREAD

**Issue by domoritz** [vega/vega-tooltip#201]
We will bring this behavior back with a Vega update. Stay tuned and follow vega/vega#1263. 

Also, see https://github.com/vega/vega-tooltip/issues/200#issuecomment-385121520

**Comment by pelotom** [comment]
Confirmed this is fixed with Vega 4, so I think it can be closed.

**Comment by domoritz** [comment]
Sweet. Do you want to send a PR to update the examples in this repo?

**Comment by pelotom** [comment]
Why do the examples need to change? It was fixed in Vega without requiring changes in `vega-tooltip` code.

**Comment by domoritz** [comment]
Oh, just update the CDN links, nothing big.
