### ISSUE TITLE
Can't parse mark's tooltip property 

### ISSUE THREAD

**Issue by plazhbanov** [vega/vega-tooltip#203]
If a tooltip is set as an object, then it's displayed as [object Object]

Here is code example:

        import * as vega from 'vega'

        var handler = new vegaTooltip.Handler(this.getToolTipConfig());
        var runtime = vega.parse(spec);
        this.view = new vega.View(runtime)
          .initialize(this.chartContainer)
          .run()

        marks: [
                {
                    type: 'symbol',
                    name: 'incidentStart',
                    from: { data: 'seasonality' },
                    interactive: true,
                    encode: {
                        enter: {
                            shape: 'circle',
                            stroke: { value: '#E74343' },
                            fill: { value: '#FFFFFF' },
                            size: { value: 90 },
                            strokeWidth: { value: 5 },
                            cursor: { value: 'pointer' }
                        },
                        update: {
                            x: { scale: 'xDetail', field: 'startUtcDate' },
                            y: { scale: 'yDetail', field: 'layer' },
                            zindex: { value: 1 },
                            opacity: { field: 'opacity' },
                            tooltip: {signal: "{date: datum.layer}"}
                        }
                    }}]

array or string works fine. 

Another issue is that View object doesn't have the tooltip function, so the example that is provided in the Readme file doesn't work

I use vega ^3.3.1

**Comment by domoritz** [comment]
Can you post a working example in a https://bl.ocks.org/? The Vega view should have a tooltip property: https://vega.github.io/vega/docs/api/view/#view_tooltip.

**Comment by plazhbanov** [comment]
vega ^3.3.1 has vega-view^2.2 as dependency, I've already posted the issue in https://github.com/vega/vega/issues/1267

vega-view^2.2 has now .tooltip function.

Anyway, I tried to check the code above using vega-view v.2.3.2 and line 
`
    tooltip: {signal: "{date: datum.layer}"}
`

doesn't work. But 
`
     tooltip: {signal: "[datum.layer]"} 
`

works fine

**Comment by plazhbanov** [comment]
Hi Dominik,

I checked all vega examples works with object notation, but the same code doesn't work in my project if I import vega via import * as vega from 'vega'.
I'll try it with an updated version of vega which is coming soon.

**Comment by domoritz** [comment]
Can you make sure that you update all Vega libraries as well. Especially the Vega view dependency.

**Comment by domoritz** [comment]
Closing as it works on master.
