### ISSUE TITLE
Support Image in tooltip

### ISSUE THREAD

**Issue by Casyfill** [vega/vega-tooltip#210]
It is fairly straightforward to add on my own, but can't see why not support this out of the box - say, by providing `image` key ? What do you think?

**Comment by domoritz** [comment]
You can put HTML in your tooltip but you would need to provide a sanitizer that accepts image tags and does not escape them.

**Comment by domoritz** [comment]
We could add support for a special image key. Can you make a proposal what this would look like?

**Comment by Casyfill** [comment]
Yeah, I was thinking of an ‘image’ key? :-)

I understand re sanitizers - for my particular task it seems simplest to use your markdown example and utilize it’s markdown image option

**Comment by Casyfill** [comment]
It would probably require image max-width Param

**Comment by domoritz** [comment]
I think this idea would be very powerful for data science/ml applications. Let me take a look.
