### ISSUE TITLE
Examples doesn't work

### ISSUE THREAD

**Issue by elderapo** [vega/vega-tooltip#211]
Examples seem to be broken:
```
TypeError: vegaEmbed is not a function
    at vega-examples.html:45
```

**Comment by domoritz** [comment]
Thank you. I'm fixing it right now.

**Comment by domoritz** [comment]
Fixed with a release of Vega-Embed 3.18.1. Once the caches update, it will work again.

**Comment by elderapo** [comment]
Still doesn't work.

**Comment by domoritz** [comment]
Try a hard refresh (shift + refresh). It works for me.
