### ISSUE TITLE
Does not work in Angular/Typescript

### ISSUE THREAD

**Issue by king612** [vega/vega-tooltip#213]
Following the documentation closely, I cannot get this to work for a Vega-Lite chart in an Angular (6) / Typescript application.  I've tried several different things.  Nothing works.  Vega just renders the HTML markup as text in the tooltip.  I've tried to manually sanitize the HTML, and I now the tooltip sanitize function is firing.  The code is on a closed system so I can't post it, but it goes something like this:

`import * as vegaTooltip from 'vega-tooltip';`
`import * as vl from 'vega-lite'`
     :
`let ttHandler = new vegaTooltip.Handler();`
`let vgSpec = vl.compile(spec).spec;;`
`let view = new vega.View(vega.parse(vgSpec))`
`    .tooltip(tthandler.call)`
    .....
`

The default sanitizer would work fine, but it apparently does nothing.  I've tried adding a sanitize function and passing it in through the options.  It fires, but even using the ....bind(this) technique, the callback context can't see the local vegaTooltip reference so just calling `vegaTooltip.escape(html)` in my own sanitize function doesn't work, such as:

`let ttHandler = new vegaTooltip.Handler({`
`    theme: 'dark',`
`    sanitize: (html) => {`
`        return String(html).replace(/</g, '&lt;');`
`    }`
`});`

This just renders the escaped HTML string in the tooltip.

The Angular documentation insists that it will render regular, 'safe' (no script tags) HTML without disabling security.  I've tried manually sanitizing the string with string replacements (just like the default function), but Angular/Vega-Lite/vegaTooltip just renders the raw string everytime.  HTML tags are just ignored as regular tooltip text.

Any help would be greatly appreciated.

**Comment by domoritz** [comment]
This seems to be an angular specific problem. I don't use angular so I can't help here.
