### ISSUE TITLE
can I use datum object value as key in tooltip

### ISSUE THREAD

**Issue by vikkya** [vega/vega-tooltip#223]
I have a dataset like {"category": "A", "value": 20, "category": "B": 50}. Can I have a tooltip as A:20, B:50.
I tried it this way "tooltip":{"signal": "{datum.category: datum.value}"}, but it throws any error. 
Can I use this way??

Thanks

**Comment by domoritz** [comment]
You can only have one category key in an object.

**Comment by vikkya** [comment]
Ok, Thank you :)

**Comment by domoritz** [comment]
If you want to use a variable as a key, you can do

```js
const a = "key"
const b = {[a]: 42}
```

**Comment by umang-gramener** [comment]
is this for vega or vega-lite
