### ISSUE TITLE
Tooltip customization instructions not working

### ISSUE THREAD

**Issue by melissachang** [vega/vega-tooltip#236]
In my Javascript:
```
              <VegaLite
                spec={spec}
                data={data}
                tooltip={new Handler({theme: "custom"}).call}
                onNewView={this.onNewView}
              />
```
css file:
```
.vg-tooltip.custom-theme {
  background-color: red;
}
```
Background color did not change because `.vg-tooltip.custom-theme background-color` is overridden by `#vg-tooltip-element background-color`.

![1](https://user-images.githubusercontent.com/10929390/54057306-6a48a380-41a7-11e9-9580-59462822f922.png)

**Comment by melissachang** [comment]
This css works:
```
#vg-tooltip-element {
  background-color: red;
}
```
![2](https://user-images.githubusercontent.com/10929390/54057693-7bde7b00-41a8-11e9-864c-683258a94049.png)

Still need the custom theme.

**Comment by domoritz** [comment]
You have to load your CSS after the CSS from the tooltip plugin, use a more specific selector, or use `!important` (discouraged).

**Comment by melissachang** [comment]
IIUC, regardless of loading order, #vg-tooltip-element takes precedence over .vg-tooltip.custom-theme [because an id has higher specificity than a class](https://stackoverflow.com/a/25105841/6447189).

Note that some properties will work. `font-weight` works because it's not in `#vg-tooltip-element`.

How about the README changes to:
```
#vg-tooltip-element.vg-tooltip.custom-theme {
  color: red;
}
```
Then it works. I'm happy to send a PR.

**Comment by domoritz** [comment]
Ahh, yes, you're right. Let's update the documentation or the default css. Which one do you think makes more sense?

**Comment by melissachang** [comment]
I'm not sure what "default css" means. The only thing I would change is, changing the last code block in the [documentation](https://github.com/vega/vega-tooltip/blob/master/docs/customizing_your_tooltip.md) to:
 ```
#vg-tooltip-element.vg-tooltip.custom-theme {
  color: red;
}
```

**Comment by domoritz** [comment]
You're right. Let's just do that. Can you send a PR?
