### ISSUE TITLE
Can I specify the order of tooltip rows?

### ISSUE THREAD

**Issue by lpkearns** [vega/vega-tooltip#347]
I'd like to be able to define what order my tooltip rows appear, so that they can be in the same order as they are in my legend (which is not a Vega legend, but one made in Vue).

Is this possible already? Or is this something you would consider adding?

**Comment by domoritz** [comment]
What’s the behavior right now? I think it would be best to just keep the order that is specified in Vega.

**Comment by lpkearns** [comment]
I realized that it's possible to reorder the tooltip rows by changing their order in the signal string. So I was able to order them how I wanted.
