### ISSUE TITLE
Vega fields that should be hidden by default in tooltip

### ISSUE THREAD

**Issue by ZeningQu** [vega/vega-tooltip#35]
![edges](https://cloud.githubusercontent.com/assets/822034/14591314/c0c7f518-04c3-11e6-8edd-5c83fee04cf2.png)

![force](https://cloud.githubusercontent.com/assets/822034/14591316/c45de66a-04c3-11e6-97b4-2201d0b30948.png)

![map](https://cloud.githubusercontent.com/assets/822034/14591319/c99dd19e-04c3-11e6-8468-92f5cea8da47.png)

**Comment by Georgeouz** [comment]
I would supplement that hiding should occur for non-user objects or fields.

**Comment by po5i** [comment]
@ZeningQu how do you make the relationship tooltip appear? For me is only working for the nodes.

Thanks.
