### ISSUE TITLE
Vega-Tooltip, Title and Padding Update

### ISSUE THREAD

**Issue by jerinjjose** [vega/vega-tooltip#385]
I am using vega-lite, vega-embed, and vega-tooltip on my angular development.
I am filled with tooltips and I want to customize the tooltip. 

- I want to reduce the padding between each tooltip Item
- Want to Increase the tooltip width
- Want to bring the color for each item in the tooltip also

Please provide the solution.

**Comment by domoritz** [comment]
You can customize the CSS.
