### ISSUE TITLE
Mute "Cannot find field" warnings for certain composition

### ISSUE THREAD

**Issue by ZeningQu** [vega/vega-tooltip#39]
When vega-lite composite is ready, we should add logic to the `getValue()` function in `vl-tooltip.js` to mute the `"[Tooltip] Cannot find field ... in data."` warnings when the field is not in a composition.

**Comment by sirahd** [comment]
@kanitw I wonder how can we determine if a certain vega-lite spec is a composition or not? Is there any function in vl I can call to determine this?

**Comment by sirahd** [comment]
Close as part of #154
