### ISSUE TITLE
Should we name this vega-tooltip as it supports both Vega and Vega-Lite?  

### ISSUE THREAD

**Issue by kanitw** [vega/vega-tooltip#42]
I'm voting for vega-tooltip?

@domoritz @arvind  @jheer – any opinion?

**Comment by jheer** [comment]
If it works well with both, go with vega-tooltip!

**Comment by kanitw** [comment]
the repo name is still vega-lite-tooltip, please rename that before closing.

**Comment by kanitw** [comment]
Done.   Please make sure all the docs use the new name and we can close this.

**Comment by ZeningQu** [comment]
Done in #46
