### ISSUE TITLE
0.24 throws an error (Te: invalid module) when loading it into Observable

### ISSUE THREAD

**Issue by john-guerra** [vega/vega-tooltip#472]
Seems likes 0.24 introduces a bug in the module configuration at least when loading into Observable. 0.23.2 still works OK. See: https://observablehq.com/d/d4d479f5a90fa995

If I can free some time will try to take a look at the code to check what happened and be more helpful

**Comment by domoritz** [comment]
Maybe related: https://github.com/vega/vega-embed/issues/557

**Comment by domoritz** [comment]
Hmm, does observable accept iife packages? https://github.com/vega/vega-tooltip/blob/4804a779b2d0d6802d726e0811ea29dbecefdb73/rollup.config.js#L46

**Comment by domoritz** [comment]
Ahh, yeah, observable needs umd (https://observablehq.com/@observablehq/how-to-require-stubborn-modules). I will fix that.
