### ISSUE TITLE
Interactive tooltip

### ISSUE THREAD

**Issue by UkonnRa** [vega/vega-tooltip#499]
Hi all,

Sometime I want to interactive with vega-tooltip, for example, I want to put some inputs inside the tooltip so that I can do some operations. But right now it seems that:

1. I cannot put HTML code into tooltip
2. I have no idea how to "pin" the tooltip somewhere
  1. I want to pin the tooltip if I do some operation (for example, I click the data point)
  2. I want the tooltip draggable

Any idea how to handle this? Thanks

**Comment by UkonnRa** [comment]
BTW, because I want to use canvas render, so JQuery draggable or something like is not usable

**Comment by domoritz** [comment]
We don't support this right now but you can easily implement your own tooltip gander to make a more interactive tooltip. 

We don't allow arbitrary html since that could be a security issue.
