### ISSUE TITLE
Allow chaining methods to update config

### ISSUE THREAD

**Issue by ZeningQu** [vega/vega-tooltip#57]
For example

``` js
vl.tooltip(vgView, vlSpec[, options])
  .showAllFields(false)
  .colorTheme('dark');
```
- [ ] update doc

**Comment by kanitw** [comment]
@ZeningQu  This seems unnecessary since users can already provide `options` ?  If this is not that different from options, let's close this.

**Comment by ZeningQu** [comment]
The only difference seems to be chaining methods allow you to change things on the fly. I agree it's not yet necessary for tooltip.
