### ISSUE TITLE
Suggestion: Tooltips for tiny bars

### ISSUE THREAD

**Issue by domoritz** [vega/vega-tooltip#68]
Imagine a bar chart with very small bars. If you want to know the exact value, you will have a hard tome hovering over a small bar. It'd be great to be able to get the tooltip on the whole column instead of just the bar.

**Comment by pheaver** [comment]
Same problem for line graphs. I'm trying to migrate to vega for a project, but it's super hard to get a tooltip to show up on a line graph. In our current graphs that I'd be migrating from, the tooltip shows up when you get close to the line, but you don't have to be exactly over it, which is nice.

**Comment by domoritz** [comment]
One solution to the problem of line charts is an overlay with a thick but invisible line.

**Comment by pheaver** [comment]
I was wondering if I could do that. Would I need to make two lines, one that is thick and invisible and gets the tooltip, and another that is the visible line?

**Comment by domoritz** [comment]
Yes. The tooltip would only be triggered by the line that is above.

**Comment by ericsoco** [comment]
This is exactly how tooltips are calculated in the application I'm migrating onto Vega -- based only on x-position, not on element hover. This strategy works well for line charts. It also works well for charts with multiple visual encodings (e.g. a line chart over a bar chart), in which case the tooltip shows the y values for everything at the current x position.

I may look into adding this to `vega-tooltip` soon, but if I don't find a good one I'll probably fall back to a vanilla JS solution instead.

**Comment by domoritz** [comment]
@ericsoco I'd love to see this in Vega-Tooltip. As a quick solution for Vega and Vega-Lite, one can add an invisible layer with rectangles that span the complete height of the chart.

**Comment by ericsoco** [comment]
After some investigation, I'm not sure x-location-based tooltips is something vega-tooltip can support out of the box, since it's dependent on the `item` returned by the scenegraph, and there is no item when not hovering on a mark. The suggestion of invisible full-height bars is a good one though, I'll try that route. Thanks @domoritz!

**Comment by domoritz** [comment]
Covers #69

**Comment by domoritz** [comment]
This isn't something we can easily solve in the tooltip library. This should be handled in Vega/Vega-Lite.

**Comment by ericsoco** [comment]
Still on my radar to submit an example, FWIW. Just trying to squeeze out the time.

**Comment by domoritz** [comment]
Great! Note that we will soon improve tooltips significantly. To prepare for that, I wanted to clean up the issues here. 

See https://github.com/vega/vega/issues/1198

**Comment by ericsoco** [comment]
I see. Read thru that and related issues, but it's not clear if this will result in any changes to the vega-tooltip API, or just to the way it connects to Vega. Do you have thoughts on this? (Are they documented in another issue on vega-tooltip?)

**Comment by domoritz** [comment]
We will move the essential parts into Vega and Vega-Lite themselves but keep some customizations in the tooltip library (e.g. themes).
