### ISSUE TITLE
Tick marktype is hard to hover over

### ISSUE THREAD

**Issue by ZeningQu** [vega/vega-tooltip#69]
Observed in user study

**Comment by kanitw** [comment]
Unless you do Voronoi or underlay a larger invisible mark for tooltip-ing.  I don't see a solution for this.   Not sure if we should do the latter though.

**Comment by domoritz** [comment]
For now, I suggest adding invisible marks. We will make some changes to this library. Until then, I'm going to close issues that are not immediately actionable.
