### ISSUE TITLE
Lift restriction on tooltip size for images

### ISSUE THREAD

**Issue by joelostblom** [vega/vega-tooltip#739]
Currently, it is not possible to display images larger than 200 pixels ydue to restrictions in their css for the max width and height:

https://github.com/vega/vega-tooltip/blob/21513103f033dc1c1b97240d31af03d4f5aa29ac/vega-tooltip.scss#L21-L24

Changing this is not straightforward as one has to manually edit the css to increase the size of the image. One of the original motivations for adding the image tooltip key was that it would be useful for data science and machine learning applications as mentioned this comment https://github.com/vega/vega-tooltip/issues/210#issuecomment-626086720. I agree with this but the current limit of 200 pixels means that it's really only icons and similar simple images that show up nicely in the tooltip. As it is easy to downsize an image if needed, I suggest that the max width/height restricted is lifted to allow the user the flexibility of choosing the size of their images themselves.

Here's an example showing a the panel of that microscope amateurs and it's really hard to see what is shown in the individual images because it's so small (while the images smaller than 200 pixels are showing up fine):

![image](https://user-images.githubusercontent.com/4560057/220440598-1a718155-11e9-443a-9bcc-ab58bf33f678.png)
[Open the Chart in the Vega Editor](https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JAKyUAVhDYA7EABoQxGnADuaUBEwAnNgGs4aWQ0GCAvkoAmSTClShiSQQzgQ0AbVA1kZI+ixcfCI1UMpMNgBPNjs2ADMmNiQdK2RZSig2BAIkHBwCHBdaWQgCK2J+HTgVdX4IYSs4HX4cPQLmYSgC5MwaZ1KfMlKyNjYyQTgAfQhkM0maTPScWTIQS29ffxAbOwI4uLYAD0pl1fWQHyQ-NAxsPEICULVKKog4ZNgKTDhKWThMAp6OI0CYEAASbhgSAQkwAooJJgAlOBxJBwSIAZnaTE6tnYsgIACYACwARgADAA2SliMTkvY0MgMKplNhqWSCJJWBlkMQEACCAGVUMSxABOAAcYtJYrJEoA7GJ5aSJQABUnEiXUsQSmUy5UEACypl6hTg-DiLjYelgegQ5qsjLozgtVteUDgsg9-EuxTI-AQCz00DYOAW-CQsmckQgNAg-Hi-H5-EWujYgn4akwJxWawAupYQMgdPpNCBMJEcFtvodMIoQM5GfJ0BM4nXC57Mo7cw5y3Ba2XgXBBFYbr6jIXIoPVCOx5t60hDnHjKYLEoIunTZ5QEPZ+hx-nzOYgA)

An even better solution would be a parameter that controls the max-width of the image, but I don't think the specification and implementation of that should delay the removal of the current limit which I see us as is a good first step and would be useful for many applications. Let me know if I am missing something here and there is a good use case for the limit.

**Comment by domoritz** [comment]
I'm okay with removing the limit. Can you send a pull request?
