### ISSUE TITLE
Supplement options from Vega spec?

### ISSUE THREAD

**Issue by ZeningQu** [vega/vega-tooltip#76]
Just like we supplement `options` with Vega-Lite spec, and apply many Vega-Lite defaults so that `vltooltip` is consistent with the vl chart, we could read a Vega spec and apply Vega defaults so that `vgtooltip` is more consistent with the vg chart.

**Comment by kanitw** [comment]
>  we could read a Vega spec and apply Vega defaults so that vgtooltip is more consistent with the vg chart.

Good luck with that...  If I were you, I'd just close this.
