### ISSUE TITLE
Allow hovering axis and legends

### ISSUE THREAD

**Issue by kanitw** [vega/vega-tooltip#78]
(Currently we only support hovering axes and legends)

**Comment by pelotom** [comment]
>(Currently we only support hovering axes and legends)

This should read “only support hovering marks”, no?

It seems that axes and legends, both their labels and titles, are hoverable by simply setting them as `interactive`. However it doesn’t seem possible, even with the new capabilities of #155, to determine which axis or legend is being hovered, only the text being hovered in the case of labels, and really no useful information at all when hovering on titles. Moreover, when hovering labels I want to show only the field pertaining to that tick on the axis, but will get warnings if the other fields are missing. And for titles I want to show a completely different schema, maybe just a blob of text describing the domain represented by the scale associated with the guide (though that kind of thing is probably out of scope for this library).

**Comment by domoritz** [comment]
We now support whatever tooltips Vega supports. So this would have to be filed again over there.
