### ISSUE TITLE
Colon use problematic with French

### ISSUE THREAD

**Issue by lreis** [vega/vega-tooltip#785]
Currently a colon is added immediately after a tooltip string: 

![Screenshot 2023-06-02 at 7 46 45 AM](https://github.com/vega/vega-tooltip/assets/509658/3d697263-af9b-4ba8-8da5-4c7eab2b6a33)

https://github.com/vega/vega-tooltip/blob/main/src/formatValue.ts#L42

In French, punctuation marks, including colon, must be preceded by a space. So, for example, "Month:" is translated as "Mois :".

Ideally the colon is part of the tooltip string, so translators can adjust it accordingly.

**Comment by domoritz** [comment]
Huh, interesting, I'd be happy to just remove the colon. Can you send a pull request?

**Comment by lreis** [comment]
@domoritz it looks like the fix may not be as simple as removing the colon, and adding them back in the [tooltip string](https://github.com/vega/vega-tooltip/blob/main/examples/specs/choropleth.json#L63): when testing my change I noticed that in some of the examples, the tooltip strings are derived from keys stored in the data files, e.g Vega-Lite Tooltip Examples > vis-scatter > "Horsepower" and "Miles_per_Gallon" (from examples / data / cars.json). It would be unreasonable to require colons to be added there, so another approach is necessary.

**Comment by npmccauslin** [comment]
Are you going to merge the PR? If not, is there a way to remove it individually? Customizing the tooltip is extremely limited with `:` being injected.

**Comment by domoritz** [comment]
There is no pull request yet.

But yes, I am okay with removing the : from the default string.
