### ISSUE TITLE
Split modules for vega and vega-light to minimize dependency load

### ISSUE THREAD

**Issue by GCheung55** [vega/vega-tooltip#99]
Current tooltips implementation requires loading vega-light code. Loading vega-light code when only vega is used for visualization increases dependency load unnecessarily.

I propose that the implementations are split into two modules/files so developers can choose that way and still use index.js to load both compatibility.

**Comment by GCheung55** [comment]
I just realized there isn't an index.js because the build only outputs a single js file. But none the less, splitting into two separate modules would be helpful.

**Comment by sirahd** [comment]
This problem is fixed in #101. The APIs remain the same, but vega-tooltip now only needs vega dependency and the same goes for vega-lite.
